server:
  port: 8080
  servlet:
    context-path: /sample-sp

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE

spring:
  security:
    saml2:
      relyingparty:
        registration:
          samlexample:
            signing.credentials:
              - private-key-location: "classpath:credentials/service-provider-private.key"
                certificate-location: "classpath:credentials/service-provider-certificate.crt"
            identityprovider:
              entity-id: http://localhost:8081/sample-idp/saml/idp/metadata
              verification.credentials:
                - certificate-location: "classpath:credentials/identity-provider-certificate.crt"
              sso-url: http://localhost:8081/sample-idp/saml/idp/select